### PR TITLE
WIP: Add manticore benchmarking

### PR DESCRIPTION
**Pull request by srisankethu**
Work in progress. Refactored code so that new analysers can be added.

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@srisankethu 

Am I getting it write, that you work on this within the Topcoder challenge? I am not sure, why you created a public PR while the challenge is still going on? You are supposed to keep the work private and submit the patch with your updates to Topcoder platform for review and scoring.

**Comment by srisankethu** [comment]
It just skipped my mind. I have been working on other projects too. So silly of me. I won't be updating this PR till the end of the challenge then.

**Comment by rocky** [comment]
Overall this looks good if incomplete. 

Since this PR is here, I'd like to offer some comments and some suggestions. 

In PR's a good practice when you clone the repository is to make a branch with the feature you want to add. So do something like: 

```
git checkout -b branch add-manticore
```

This is called a "feature branch". And it allows the feature to be tracked independently. You can still issue a command like the above in your repository or a checked-out version of that. 

With this you would submit (eventually) a pull request from the branch you checked out. Thanks.

**Comment by rocky** [comment]
One other thing I should mention with regards to the analysis part that in this Pull Request. 

As was mentioned, Manticore doesn't have a JSON output. So for that what would be slick to do is to parse it as text after the runner/run.py but save it in a Python structure that is JSON compatible. That is use lists and diectionaries and the values inside that should be strings, integers, booleans, floats adn so on.  With that then write that out as JSON to output in run. 

From there analysis py  would read it back the JSON. 

Thanks.

**Comment by srisankethu** [comment]
@rocky Thank you for your suggestions :+1:

**Comment by rocky** [comment]
I just realized I misspoke. I had said to write and read out in JSON. I realize that in fact I used YAML. 

In theory either is fine and they are interchangeable. In practice YAML would be easier on future developers to work with. 

It is not a big deal JSON vs YAML, so if you've gone down the JSON path and don't want to switch to YAML that's okay.

**Comment by srisankethu** [comment]
@rocky Closing this as I wasn't able to complete it(contest).

**Comment by srisankethu** [comment]
@rocky I did not submit on Topcoder. I forgot about the deadline time. Saw it 2 hrs late. Anyway thanks for the feedback.

**Comment by srisankethu** [comment]
@rocky Hello, Nikhil has reached to me. How may I contact you on discord?

**Comment by rocky** [comment]
@srisankethu Join discord with https://discord.gg/apNNsR on their you should see me logged in as rocky#2336

**Pull request closed without merging**
